/* ═══════════════════════════════════════════════════════════════
   Local Brain — Massive Offline Intelligence Engine v2
   100+ topik, fuzzy matching, zero API dependency.
   ═══════════════════════════════════════════════════════════════ */

interface KnowledgeEntry {
  keywords: string[];
  response: string;
}

const KB: KnowledgeEntry[] = [
  // ══════════════════════ GREETINGS & SOCIAL ══════════════════════
  { keywords: ['halo','hai','hi','hey','hallo','hello','p','woi','woy'], response: `Halo! 👋 Saya **AppForge AI**, asisten kecerdasan buatan Anda.\n\nSaya memiliki dua kemampuan utama:\n- 🧠 Menjawab pertanyaan tentang **berbagai topik** secara mendalam\n- 🏗️ Membangun **aplikasi web** dari deskripsi yang Anda berikan\n\nSilakan ajukan pertanyaan apa pun, atau instruksikan saya untuk membangun sesuatu.` },
  { keywords: ['selamat pagi','pagi'], response: `Selamat pagi! ☀️ Semoga hari Anda berjalan dengan baik. Ada yang bisa saya bantu hari ini?` },
  { keywords: ['selamat siang','siang'], response: `Selamat siang! 🌤️ Saya siap membantu Anda. Silakan ajukan pertanyaan atau instruksi Anda.` },
  { keywords: ['selamat sore','sore'], response: `Selamat sore! 🌅 Ada yang bisa saya bantu sore ini?` },
  { keywords: ['selamat malam','malam'], response: `Selamat malam! 🌙 Saya tetap beroperasi penuh di malam hari. Ada yang bisa saya bantu?` },
  { keywords: ['terima kasih','makasih','thanks','thank you','thx','nuhun'], response: `Sama-sama! 😊 Senang bisa membantu Anda. Jangan ragu untuk bertanya lagi kapan pun Anda membutuhkan bantuan.` },
  { keywords: ['kamu siapa','siapa kamu','who are you','siapa nama','namamu'], response: `Saya adalah **AppForge AI**, sebuah asisten kecerdasan buatan yang dirancang untuk dua tujuan utama: menjawab pertanyaan Anda secara mendalam, dan membangun aplikasi web secara otomatis berdasarkan instruksi Anda.\n\nSistem saya dilengkapi dengan:\n- 🧠 Basis pengetahuan luas yang mencakup lebih dari 100 topik\n- 🔍 Koneksi ke ensiklopedia publik untuk informasi terkini\n- 🏗️ Mesin pembangunan aplikasi yang bekerja secara langsung (real-time)\n\nSilakan coba ajukan pertanyaan apa pun.` },
  { keywords: ['bisa apa','kemampuan','fitur','apa yang bisa','help','bantuan'], response: `🚀 **Kemampuan Saya:**\n\n**🧠 Tanya Jawab Mendalam:**\nTeknologi, Pemrograman, Kecerdasan Buatan, Sains, Matematika, Sejarah, Geografi, Tokoh Dunia, Bisnis, Kesehatan, Olahraga, Musik, Film, dan berbagai topik lainnya.\n\n**🏗️ Pembangunan Aplikasi:**\nAnda bisa memberikan instruksi seperti:\n- *"Buatkan toko online dengan tema biru"*\n- *"Buatkan dashboard analitik untuk penjualan"*\n- *"Buatkan portofolio web dengan tema gelap"*\n\nSaya akan langsung membangun kode sumbernya secara real-time di hadapan Anda.` },
  { keywords: ['apa kabar','kabar','how are you'], response: `Terima kasih sudah bertanya! 😊 Sebagai sistem kecerdasan buatan, saya selalu dalam kondisi optimal dan siap beroperasi kapan pun Anda membutuhkan. Ada yang bisa saya bantu?` },
  { keywords: ['joke','jokes','lucu','lelucon','lawak'], response: `Baiklah, berikut sedikit humor untuk Anda! 😄\n\n**Mengapa programmer lebih suka bekerja dalam kegelapan?**\nKarena mereka tidak ingin bertemu *bugs* (serangga)! 🐛\n\n**Mengapa koneksi WiFi sering terputus saat hujan?**\nKarena jaringannya *basah*! 🌧️\n\nJika Anda ingin membahas topik yang lebih serius, saya juga siap membantu. 😊` },


  // ══════════════════════ PROGRAMMING & TECH ══════════════════════
  // General
  { keywords: ['pemrograman','programming','coding','koding','ngoding','programmer','coder','kode','program'], response: `**Pemrograman** adalah proses menulis instruksi yang dapat dimengerti oleh komputer untuk menyelesaikan suatu tugas.\n\n**Bahasa Pemrograman Populer:**\n- 💛 **JavaScript** — Bahasa utama untuk pengembangan web (frontend dan backend)\n- 🐍 **Python** — Pilihan utama untuk kecerdasan buatan, data science, dan otomasi\n- ☕ **Java** — Dominan di dunia enterprise dan pengembangan Android\n- 💙 **TypeScript** — JavaScript dengan sistem tipe statis untuk proyek berskala besar\n- 🦀 **Rust** — Bahasa modern dengan fokus pada keamanan memori dan performa tinggi\n- 💜 **C#** — Bahasa utama untuk pengembangan game (Unity) dan aplikasi Windows\n\n**Langkah Memulai:**\n1. Pilih satu bahasa (JavaScript atau Python sangat direkomendasikan untuk pemula)\n2. Pelajari konsep dasar: variabel, kondisi, perulangan, dan fungsi\n3. Bangun proyek kecil untuk memperkuat pemahaman\n4. Konsisten berlatih setiap hari, meskipun hanya 30 menit\n\nPemrograman adalah keterampilan yang paling dicari di era digital saat ini. 💻` },
  { keywords: ['komputer','computer','pc','laptop'], response: `**Komputer** adalah mesin elektronik yang memproses data sesuai dengan instruksi yang diberikan (program).\n\n**Komponen Utama:**\n- 🧠 **CPU (Processor)** — Otak komputer yang menjalankan kalkulasi\n- 💾 **RAM** — Memori sementara untuk menyimpan data yang sedang diproses\n- 💿 **Storage (SSD/HDD)** — Penyimpanan data permanen\n- 🎮 **GPU** — Prosesor grafis untuk rendering visual dan komputasi paralel\n- 🔌 **Motherboard** — Papan sirkuit utama yang menghubungkan semua komponen\n\n**Sistem Operasi Populer:** Windows, macOS, Linux\n\nKomputer modern mampu melakukan triliunan kalkulasi per detik, menjadikannya fondasi dari hampir seluruh teknologi yang kita gunakan sehari-hari. 🖥️` },
  { keywords: ['internet','wifi','jaringan','network','web','www'], response: `**Internet** adalah jaringan global yang menghubungkan miliaran perangkat komputer di seluruh dunia.\n\n**Cara Kerja (Sederhana):**\n1. Anda mengetikkan alamat web (misalnya google.com) di browser\n2. Browser mengirim permintaan ke server DNS untuk menemukan alamat IP server tujuan\n3. Server tujuan mengirim kembali data halaman web kepada browser Anda\n4. Browser merender data tersebut menjadi tampilan visual\n\n**Fakta:**\n- 🌐 Internet diciptakan pada tahun 1969 sebagai proyek ARPANET oleh Departemen Pertahanan Amerika Serikat\n- 📡 Lebih dari **5,3 miliar orang** menggunakan internet (sekitar 66% populasi dunia)\n- 🌊 Sebagian besar data internet ditransmisikan melalui **kabel bawah laut** yang membentang di dasar samudra\n\nInternet adalah infrastruktur paling transformatif dalam sejarah umat manusia. 🌍` },
  { keywords: ['bumi','earth','planet bumi','dunia'], response: `🌍 **Bumi** adalah planet ketiga dari Matahari dan satu-satunya planet yang diketahui mendukung kehidupan.\n\n**Fakta Ilmiah:**\n- 🌏 **Diameter:** 12.742 kilometer\n- 🌊 **Permukaan air:** 71% (oleh karena itu dijuluki \"Planet Biru\")\n- 🏔️ **Titik tertinggi:** Gunung Everest (8.849 meter)\n- 🌊 **Titik terdalam:** Palung Mariana (10.994 meter)\n- 👥 **Populasi:** lebih dari 8 miliar manusia\n- 🔄 **Rotasi:** 23 jam 56 menit (menghasilkan siklus siang dan malam)\n- ☀️ **Revolusi:** 365,25 hari mengelilingi Matahari\n- 🌡️ **Suhu rata-rata:** 15°C\n\n**Lapisan Bumi:** Kerak (crust), Mantel (mantle), Inti luar (outer core), Inti dalam (inner core)\n\nBumi berusia sekitar **4,5 miliar tahun** dan merupakan rumah bagi jutaan spesies makhluk hidup. 🌎` },
  { keywords: ['teknologi','technology','tech'], response: `**Teknologi** adalah penerapan pengetahuan ilmiah untuk tujuan praktis, terutama dalam bidang industri dan kehidupan sehari-hari.\n\n**Perkembangan Teknologi Penting:**\n- 🖨️ **Mesin Cetak** (1440) — Mempercepat penyebaran informasi\n- ⚡ **Listrik** (1879) — Fondasi peradaban modern\n- 📞 **Telepon** (1876) — Revolusi komunikasi jarak jauh\n- 💻 **Komputer** (1945) — Mesin pengolah data universal\n- 🌐 **Internet** (1969) — Menghubungkan seluruh dunia\n- 📱 **Smartphone** (2007) — Komputer dalam genggaman tangan\n- 🤖 **Kecerdasan Buatan** (2020-an) — Mesin yang dapat berpikir dan belajar\n\nTeknologi terus berkembang secara eksponensial. Kekuatan komputasi yang dahulu memenuhi satu ruangan kini tersedia di dalam ponsel Anda. 🚀` },
  // Languages
  { keywords: ['react','reactjs'], response: `**React** adalah library JavaScript dari **Meta (Facebook)** untuk membangun UI.\n\n**Fitur Utama:**\n- ⚛️ **Component-Based** — UI dipecah menjadi komponen reusable\n- 🔄 **Virtual DOM** — Hanya update bagian yang berubah\n- 🪝 **Hooks** — useState, useEffect, useContext\n- 📱 **React Native** — Untuk aplikasi mobile\n\n\`\`\`jsx\nfunction App() {\n  const [count, setCount] = useState(0);\n  return <button onClick={() => setCount(c => c+1)}>Klik: {count}</button>;\n}\n\`\`\`\n\nReact digunakan oleh Facebook, Instagram, Netflix, Airbnb, dan ribuan perusahaan lainnya! ⚛️` },
  { keywords: ['javascript','js','ecmascript'], response: `**JavaScript** adalah bahasa pemrograman #1 di dunia untuk web. Dibuat oleh **Brendan Eich** pada 1995.\n\n**Kegunaan:**\n- 🌐 Frontend (React, Vue, Angular)\n- 🖥️ Backend (Node.js, Deno, Bun)\n- 📱 Mobile (React Native, Ionic)\n- 🎮 Game (Phaser, Three.js)\n\n\`\`\`javascript\nconst greet = (name) => \`Hello, \${name}!\`;\nconst data = await fetch('/api/users').then(r => r.json());\n\`\`\`\n\nMenurut survei Stack Overflow, JS adalah bahasa paling populer 11 tahun berturut-turut! 💛` },
  { keywords: ['python'], response: `**Python** 🐍 adalah bahasa pemrograman yang terkenal karena sintaksnya yang simpel dan mudah dibaca.\n\n**Digunakan untuk:**\n- 🤖 AI & Machine Learning (TensorFlow, PyTorch)\n- 📊 Data Science (Pandas, NumPy)\n- 🌐 Web (Django, Flask, FastAPI)\n- 🔬 Riset Ilmiah\n- 🤖 Otomasi & Scripting\n\n\`\`\`python\nfor i in range(10):\n    print(f"Hello ke-{i}")\n\nsquares = [x**2 for x in range(10)]\n\`\`\`\n\nDiciptakan oleh **Guido van Rossum** (1991). Python adalah bahasa kedua terpopuler di dunia setelah JavaScript.` },
  { keywords: ['typescript','ts'], response: `**TypeScript** adalah superset JavaScript dengan **static typing**. Dibuat oleh **Microsoft**.\n\n**Keunggulan:**\n- ✅ Deteksi error sebelum runtime\n- 🧠 Autocomplete & IntelliSense lebih pintar\n- 📦 Ideal untuk proyek besar\n\n\`\`\`typescript\ninterface User {\n  name: string;\n  age: number;\n}\nconst greet = (user: User): string => \`Hello, \${user.name}!\`;\n\`\`\`\n\nDigunakan oleh Google, Microsoft, Airbnb, Slack, dan banyak lagi! 💙` },
  { keywords: ['html'], response: `**HTML** (HyperText Markup Language) adalah bahasa markup standar untuk membuat halaman web.\n\n\`\`\`html\n<!DOCTYPE html>\n<html>\n  <head><title>Web Saya</title></head>\n  <body>\n    <h1>Hello World!</h1>\n    <p>Ini paragraf.</p>\n  </body>\n</html>\n\`\`\`\n\nHTML adalah **fondasi semua website** di internet. Diciptakan oleh **Tim Berners-Lee** pada 1991. 🌐` },
  { keywords: ['css','stylesheet'], response: `**CSS** (Cascading Style Sheets) adalah bahasa untuk mendesain tampilan web.\n\n**Kemampuan Modern:**\n- 🎨 Flexbox & Grid Layout\n- ✨ Animasi & Transisi\n- 📱 Media Queries (responsif)\n- 🌈 Custom Properties (variabel)\n\n\`\`\`css\n.card {\n  background: linear-gradient(135deg, #667eea, #764ba2);\n  border-radius: 16px;\n  box-shadow: 0 10px 30px rgba(0,0,0,0.3);\n}\n\`\`\`\n\nCSS3 memungkinkan desain web yang sangat indah tanpa JavaScript! 🎨` },
  { keywords: ['nodejs','node.js','node js','node','needjs','nodjs'], response: `**Node.js** adalah lingkungan runtime yang memungkinkan JavaScript berjalan di sisi server (di luar browser).\\n\\nNode.js dibangun di atas mesin **V8** milik Google Chrome, sehingga performanya sangat cepat.\\n\\n**Keunggulan Utama:**\\n- ⚡ **Non-blocking I/O** — Mampu menangani ribuan koneksi bersamaan tanpa menunggu satu per satu\\n- 📦 **npm** — Repositori paket terbesar di dunia dengan lebih dari 2 juta paket\\n- 🔄 **Full-Stack JavaScript** — Satu bahasa untuk frontend dan backend\\n\\n\\\`\\\`\\\`javascript\\nconst express = require('express');\\nconst app = express();\\napp.get('/api/hello', (req, res) => res.json({ pesan: 'Halo!' }));\\napp.listen(3000, () => console.log('Server berjalan di port 3000'));\\n\\\`\\\`\\\`\\n\\nDiciptakan oleh **Ryan Dahl** pada tahun 2009. Digunakan oleh Netflix, PayPal, LinkedIn, dan Walmart. 💚` },
  { keywords: ['vue','vuejs'], response: `**Vue.js** adalah framework JavaScript progresif untuk membangun antarmuka pengguna. Dibuat oleh **Evan You**.\\n\\n**Keunggulan:** Kurva pembelajaran yang landai, ukuran ringan, dan Composition API yang sangat fleksibel.\\n\\nVue digunakan oleh Alibaba, Xiaomi, GitLab, dan banyak perusahaan lainnya. 💚` },
  { keywords: ['angular'], response: `**Angular** adalah framework web lengkap yang dikembangkan oleh **Google**. Menggunakan TypeScript sebagai bahasa utamanya.\\n\\n**Fitur Utama:** Dependency Injection, CLI yang sangat powerful, dan Two-way data binding.\\n\\nAngular sangat cocok untuk membangun aplikasi enterprise berskala besar yang memerlukan struktur ketat. 🅰️` },
  { keywords: ['php'], response: `**PHP** (Hypertext Preprocessor) adalah bahasa pemrograman server-side yang menguasai sekitar **77% website di seluruh internet**.\\n\\n**Digunakan oleh:** WordPress, Facebook (pada awalnya), Wikipedia.\\n\\n\\\`\\\`\\\`php\\n<?php\\necho "Hello World!";\\n$users = DB::table('users')->where('active', true)->get();\\n?>\\n\\\`\\\`\\\`\\n\\nDiciptakan oleh **Rasmus Lerdorf** pada tahun 1994. Framework paling populer untuk PHP adalah **Laravel** dan **Symfony**. 🐘` },
  { keywords: ['laravel'], response: `**Laravel** adalah framework PHP paling populer di dunia, dirancang untuk mempermudah pengembangan aplikasi web dengan sintaks yang elegan dan ekspresif.\\n\\n**Fitur Utama:**\\n- 🗂️ **Eloquent ORM** — Cara elegan untuk berinteraksi dengan database tanpa menulis SQL mentah\\n- 🛣️ **Routing** — Sistem rute yang bersih dan mudah dibaca\\n- 🔐 **Authentication** — Sistem login dan registrasi yang sudah tersedia secara bawaan\\n- 📨 **Queue & Jobs** — Pemrosesan tugas berat di latar belakang\\n- 🧪 **Artisan CLI** — Perintah terminal untuk mempercepat pengembangan\\n- 🔧 **Blade** — Template engine bawaan yang ringan dan intuitif\\n\\n\\\`\\\`\\\`php\\n// Contoh Route di Laravel\\nRoute::get('/users', function () {\\n    return User::all();\\n});\\n\\\`\\\`\\\`\\n\\nDiciptakan oleh **Taylor Otwell** pada tahun 2011. Laravel memiliki komunitas yang sangat besar dan ekosistem lengkap (Forge, Vapor, Nova, Livewire). 🔴` },
  { keywords: ['localhost','lokal host','local host','lokal server','server lokal','127.0.0.1'], response: `**Localhost** adalah istilah yang merujuk pada komputer Anda sendiri ketika berfungsi sebagai server.\\n\\nKetika Anda menjalankan sebuah aplikasi web secara lokal (misalnya dengan perintah \\\`npm run dev\\\` atau \\\`php artisan serve\\\`), aplikasi tersebut berjalan di komputer Anda dan dapat diakses melalui alamat **http://localhost** diikuti nomor port.\\n\\n**Penjelasan Teknis:**\\n- 🖥️ **localhost** = alamat IP **127.0.0.1** (menunjuk ke komputer Anda sendiri)\\n- 🔢 **Port** = nomor yang membedakan layanan (misalnya :3000, :5173, :8080)\\n- 🌐 **http://localhost:5173** berarti Anda mengakses aplikasi yang berjalan di port 5173 pada komputer Anda\\n\\n**Contoh Penggunaan:**\\n- \\\`npm run dev\\\` → biasanya berjalan di http://localhost:5173\\n- \\\`php artisan serve\\\` → biasanya berjalan di http://localhost:8000\\n- \\\`python -m http.server\\\` → biasanya berjalan di http://localhost:8000\\n\\nLocalhost sangat berguna untuk menguji aplikasi sebelum di-deploy ke server publik (internet). 🏠` },
  { keywords: ['env','dotenv','.env','environment variable','variabel lingkungan','konfigurasi'], response: `**File .env (Environment Variables)** adalah file konfigurasi yang menyimpan pengaturan sensitif yang tidak boleh ditulis langsung di dalam kode sumber.\\n\\n**Mengapa .env Penting:**\\n- 🔐 Menyimpan **API Key**, password database, dan rahasia lainnya secara aman\\n- 🔄 Memudahkan pergantian konfigurasi antara lingkungan **development** dan **production**\\n- 🚫 File .env **tidak boleh** di-upload ke GitHub (harus dimasukkan ke .gitignore)\\n\\n**Contoh Isi File .env:**\\n\\\`\\\`\\\`\\nDATABASE_URL=mysql://user:password@localhost:3306/mydb\\nAPI_KEY=sk-abc123xyz456\\nPORT=3000\\nNODE_ENV=development\\n\\\`\\\`\\\`\\n\\n**Cara Menggunakan di JavaScript (Node.js):**\\n\\\`\\\`\\\`javascript\\nrequire('dotenv').config();\\nconst apiKey = process.env.API_KEY;\\n\\\`\\\`\\\`\\n\\nHampir semua proyek profesional menggunakan file .env untuk mengelola konfigurasi. 📋` },
  { keywords: ['npm','yarn','pnpm','package manager','manajer paket'], response: `**npm (Node Package Manager)** adalah manajer paket bawaan Node.js dan merupakan repositori paket JavaScript terbesar di dunia.\\n\\n**Perintah Dasar npm:**\\n\\\`\\\`\\\`bash\\nnpm init              # Membuat proyek baru\\nnpm install express   # Menginstal paket 'express'\\nnpm run dev           # Menjalankan skrip 'dev'\\nnpm run build         # Membangun proyek untuk produksi\\n\\\`\\\`\\\`\\n\\n**Alternatif npm:**\\n- 🧶 **Yarn** — Dibuat oleh Facebook, lebih cepat dan deterministik\\n- ⚡ **pnpm** — Paling hemat ruang disk karena menggunakan symlink\\n\\n**package.json** adalah file konfigurasi utama yang mencatat semua dependensi dan skrip proyek Anda. 📦` },
  { keywords: ['framework','library','pustaka','kerangka kerja'], response: `**Framework** dan **Library** adalah dua konsep fundamental dalam pengembangan perangkat lunak.\\n\\n**Framework** (Kerangka Kerja):\\nMemberikan struktur lengkap untuk membangun aplikasi. Framework menentukan bagaimana kode Anda harus diorganisir.\\n- Contoh: Laravel, Angular, Django, Spring Boot, Next.js\\n\\n**Library** (Pustaka):\\nKumpulan fungsi yang bisa Anda panggil sesuai kebutuhan, tanpa mendikte struktur proyek.\\n- Contoh: React, Lodash, Axios, jQuery\\n\\n**Analogi Sederhana:**\\n- **Framework** = Rumah yang sudah dibangun, Anda hanya perlu mengisi perabotnya\\n- **Library** = Toko perabot, Anda memilih sendiri apa yang dibutuhkan dan menatanya sesuka hati\\n\\nPerbedaan kuncinya terletak pada **Inversion of Control**: framework yang memanggil kode Anda, sedangkan library yang Anda panggil. 🏗️` },
  { keywords: ['terminal','command line','cmd','powershell','bash','shell','cli','command prompt'], response: `**Terminal** (atau Command Line Interface) adalah antarmuka berbasis teks untuk berinteraksi dengan komputer.\\n\\n**Jenis Terminal:**\\n- 🪟 **Command Prompt (cmd)** — Terminal bawaan Windows\\n- 💙 **PowerShell** — Terminal modern Windows dengan fitur lebih lengkap\\n- 🐧 **Bash** — Terminal standar Linux dan macOS\\n- 🖥️ **Terminal** — Nama umum di macOS\\n\\n**Perintah Dasar yang Sering Digunakan:**\\n\\\`\\\`\\\`bash\\ncd folder_name    # Pindah ke direktori\\nls / dir          # Melihat isi direktori\\nmkdir nama_folder # Membuat folder baru\\nrm / del          # Menghapus file\\ncat / type        # Melihat isi file\\n\\\`\\\`\\\`\\n\\nProgrammer profesional menghabiskan sebagian besar waktunya di terminal karena lebih cepat dan efisien dibandingkan menggunakan mouse. ⌨️` },
  { keywords: ['vscode','visual studio code','vs code','code editor','editor kode','ide'], response: `**Visual Studio Code (VS Code)** adalah editor kode sumber gratis yang dikembangkan oleh **Microsoft**. VS Code adalah editor paling populer di dunia saat ini.\\n\\n**Mengapa Sangat Populer:**\\n- 🧩 **Ekstensi** — Ribuan plugin untuk hampir semua bahasa dan framework\\n- 🧠 **IntelliSense** — Autocomplete cerdas yang memahami konteks kode Anda\\n- 🐛 **Debugger** — Alat debugging terintegrasi langsung\\n- 🔀 **Git Integration** — Kontrol versi langsung dari editor\\n- 🖥️ **Terminal Bawaan** — Tidak perlu berpindah aplikasi\\n\\n**Ekstensi Wajib:** Prettier, ESLint, GitLens, Thunder Client, Live Server\\n\\nVS Code digunakan oleh lebih dari **70% developer profesional** di seluruh dunia. 💙` },
  { keywords: ['vite','vitejs'], response: `**Vite** adalah build tool modern untuk pengembangan web yang dibuat oleh **Evan You** (pencipta Vue.js).\\n\\n**Mengapa Vite Sangat Cepat:**\\n- ⚡ Menggunakan **ES Modules** secara native (tidak perlu bundling saat development)\\n- 🔥 **Hot Module Replacement (HMR)** yang instan\\n- 📦 Menggunakan **Rollup** untuk build produksi yang optimal\\n\\nVite mendukung React, Vue, Svelte, dan framework lainnya. Aplikasi AppForge AI yang sedang Anda gunakan ini juga dibangun menggunakan Vite. ⚡` },
  { keywords: ['nextjs','next.js','next js'], response: `**Next.js** adalah framework React yang dikembangkan oleh **Vercel** untuk membangun aplikasi web full-stack.\\n\\n**Fitur Utama:**\\n- 🖥️ **Server-Side Rendering (SSR)** — Halaman di-render di server untuk performa dan SEO yang lebih baik\\n- 📄 **Static Site Generation (SSG)** — Halaman di-generate saat build time\\n- 🛣️ **File-based Routing** — Struktur folder otomatis menjadi rute\\n- 🔌 **API Routes** — Backend API langsung di dalam proyek\\n\\nNext.js digunakan oleh TikTok, Netflix, Twitch, Nike, dan Hulu. ▲` },
  { keywords: ['tailwind','tailwindcss','tailwind css'], response: `**Tailwind CSS** adalah framework CSS yang menggunakan pendekatan **utility-first**, di mana Anda menyusun tampilan langsung menggunakan class-class kecil.\\n\\n\\\`\\\`\\\`html\\n<button class="bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600">\\n  Klik Saya\\n</button>\\n\\\`\\\`\\\`\\n\\n**Keunggulan:** Pengembangan sangat cepat, tidak perlu berpindah antara file HTML dan CSS, ukuran file produksi sangat kecil. 🎨` },
  { keywords: ['bootstrap'], response: `**Bootstrap** adalah framework CSS paling populer untuk membangun website responsif dengan cepat. Awalnya dikembangkan oleh **Twitter**.\\n\\nBootstrap menyediakan komponen UI siap pakai seperti tombol, navbar, kartu, modal, dan grid system yang responsif. Sangat cocok untuk prototyping cepat. 🅱️` },
  { keywords: ['json','xml','yaml'], response: `**JSON (JavaScript Object Notation)** adalah format data ringan yang digunakan untuk pertukaran data antar aplikasi.\\n\\n\\\`\\\`\\\`json\\n{\\n  "nama": "Dio",\\n  "umur": 20,\\n  "bahasa": ["JavaScript", "Python", "PHP"]\\n}\\n\\\`\\\`\\\`\\n\\n**JSON** adalah format data paling populer untuk API modern. Hampir semua aplikasi web menggunakan JSON untuk mengirim dan menerima data. 📋` },
  { keywords: ['hosting','deploy','deployment','server hosting','vercel','netlify','heroku'], response: `**Hosting** adalah layanan yang menyediakan ruang di server agar website atau aplikasi Anda dapat diakses melalui internet.\\n\\n**Jenis Hosting:**\\n- 🌐 **Shared Hosting** — Server dipakai bersama (murah, cocok untuk web sederhana)\\n- 🖥️ **VPS** — Server virtual pribadi (lebih cepat dan fleksibel)\\n- ☁️ **Cloud Hosting** — AWS, Google Cloud, Azure (skalabel)\\n- 🚀 **Serverless** — Vercel, Netlify (otomatis, tanpa kelola server)\\n\\n**Platform Populer untuk Developer:**\\n- ▲ **Vercel** — Terbaik untuk Next.js dan React\\n- 🌐 **Netlify** — Cocok untuk situs statis dan JAMstack\\n- 🚂 **Railway** — Alternatif Heroku yang modern\\n\\nDeploy = proses memasang aplikasi Anda ke server sehingga bisa diakses oleh semua orang di internet. 🚀` },
  { keywords: ['domain','dns','url','alamat web'], response: `**Domain** adalah nama alamat website yang mudah diingat manusia (misalnya google.com).\\n\\n**DNS (Domain Name System)** adalah sistem yang menerjemahkan domain menjadi alamat IP server. Ibaratnya, DNS adalah buku telepon internet.\\n\\n**Contoh:** Ketika Anda mengetik google.com, DNS menerjemahkannya menjadi 142.250.185.14 sehingga browser tahu harus menghubungi server mana. 🌐` },
  { keywords: ['http','https','ssl','tls','protokol'], response: `**HTTP** (HyperText Transfer Protocol) adalah protokol komunikasi yang digunakan browser untuk meminta data dari server.\\n\\n**HTTPS** = HTTP + **SSL/TLS** (enkripsi). Data yang dikirim terenkripsi sehingga tidak bisa dibaca oleh pihak ketiga.\\n\\n**Metode HTTP:**\\n- **GET** — Mengambil data\\n- **POST** — Mengirim data baru\\n- **PUT** — Memperbarui data\\n- **DELETE** — Menghapus data\\n\\nSemua website modern wajib menggunakan HTTPS untuk keamanan pengguna. 🔒` },
  { keywords: ['port','port number'], response: `**Port** adalah nomor identifikasi yang digunakan untuk membedakan layanan yang berjalan di satu komputer.\\n\\n**Port yang Sering Digunakan:**\\n- 🌐 **80** — HTTP (website)\\n- 🔒 **443** — HTTPS (website aman)\\n- 💾 **3306** — MySQL (database)\\n- 🟢 **3000** — Node.js / React development\\n- ⚡ **5173** — Vite development server\\n- 🔴 **8000** — Laravel / Django\\n- 🐘 **5432** — PostgreSQL\\n\\nKetika Anda melihat alamat http://localhost:5173, angka 5173 adalah nomor port tempat aplikasi Anda berjalan. 🔢` },
  { keywords: ['debug','debugging','error','bug','galat','kesalahan kode'], response: `**Debugging** adalah proses menemukan dan memperbaiki kesalahan (bug) dalam kode program.\\n\\n**Jenis Error Umum:**\\n- 🔴 **Syntax Error** — Kesalahan penulisan kode (tanda kurung hilang, titik koma lupa)\\n- 🟡 **Runtime Error** — Error yang terjadi saat program berjalan (pembagian dengan nol, variabel undefined)\\n- 🔵 **Logic Error** — Kode berjalan tanpa error, tetapi hasilnya salah\\n\\n**Tips Debugging:**\\n1. Baca pesan error dengan teliti — biasanya sudah menjelaskan masalahnya\\n2. Gunakan \\\`console.log()\\\` untuk melihat nilai variabel\\n3. Gunakan debugger bawaan editor (breakpoint)\\n4. Cari pesan error di Google atau Stack Overflow\\n\\n*\"Debugging adalah seperti menjadi detektif dalam film kriminal di mana Anda sendiri juga adalah tersangkanya.\"* 🐛` },
  { keywords: ['server','web server','apache','nginx'], response: `**Server** adalah komputer (atau program) yang menyediakan layanan kepada komputer lain (client) melalui jaringan.\\n\\n**Web Server Populer:**\\n- 🟢 **Nginx** — Web server tercepat dan paling efisien, digunakan oleh lebih dari 34% website di dunia\\n- 🔴 **Apache** — Web server tertua dan paling stabil\\n- 🟡 **Express.js** — Web server ringan untuk Node.js\\n\\n**Analogi:** Server adalah pelayan restoran yang menerima pesanan (request) dari tamu (client/browser) dan membawakan makanan (response/data). 🖥️` },
  { keywords: ['django','flask','fastapi'], response: `**Django**, **Flask**, dan **FastAPI** adalah framework web populer untuk bahasa **Python**.\\n\\n- 🏰 **Django** — Framework lengkap (\"batteries included\") untuk aplikasi besar. Digunakan oleh Instagram dan Pinterest.\\n- 🧪 **Flask** — Framework minimalis dan fleksibel untuk proyek kecil hingga menengah.\\n- ⚡ **FastAPI** — Framework modern dan tercepat untuk membangun API. Mendukung async dan auto-dokumentasi.\\n\\nJika Anda sudah menguasai Python dan ingin membangun web, ketiga framework ini adalah pilihan terbaik. 🐍` },
  { keywords: ['spring','spring boot'], response: `**Spring Boot** adalah framework Java yang paling populer untuk membangun aplikasi enterprise dan microservices.\\n\\nSpring Boot menyederhanakan konfigurasi Spring Framework yang kompleks menjadi pendekatan \"convention over configuration\". Digunakan oleh banyak perusahaan besar di dunia perbankan, e-commerce, dan teknologi. ☕` },
  { keywords: ['express','expressjs','express.js'], response: `**Express.js** adalah framework web minimalis dan fleksibel untuk **Node.js**. Express adalah framework backend JavaScript yang paling banyak digunakan di dunia.\\n\\n\\\`\\\`\\\`javascript\\nconst express = require('express');\\nconst app = express();\\n\\napp.get('/api/users', (req, res) => {\\n  res.json([{ nama: 'Dio', umur: 20 }]);\\n});\\n\\napp.listen(3000);\\n\\\`\\\`\\\`\\n\\nExpress digunakan sebagai bagian dari stack MERN (MongoDB, Express, React, Node.js). 🟢` },
  { keywords: ['svelte','sveltekit'], response: `**Svelte** adalah framework JavaScript yang mengkompilasi komponen menjadi kode vanilla JavaScript murni pada saat build time, sehingga tidak memerlukan runtime library di browser.\\n\\nHasilnya: aplikasi yang jauh lebih kecil dan lebih cepat dibanding React atau Vue. **SvelteKit** adalah framework full-stack di atas Svelte. 🔥` },
  { keywords: ['flutter','dart'], response: `**Flutter** adalah framework dari **Google** untuk membangun aplikasi mobile, web, dan desktop dari satu basis kode menggunakan bahasa **Dart**.\\n\\n**Keunggulan:** Satu kode untuk iOS, Android, Web, dan Desktop. Widget yang sangat kustomisasi dan performa mendekati native.\\n\\nFlutter digunakan oleh Google Ads, BMW, Alibaba, dan banyak lagi. 💙` },
  { keywords: ['react native','reactnative'], response: `**React Native** adalah framework dari **Meta** untuk membangun aplikasi mobile iOS dan Android menggunakan JavaScript dan React.\\n\\nBerbeda dengan webview, React Native merender komponen native sesungguhnya, sehingga performanya mendekati aplikasi native murni.\\n\\nDigunakan oleh Facebook, Instagram, Discord, dan Shopify. 📱` },
  { keywords: ['linux','ubuntu','debian','fedora'], response: `**Linux** adalah sistem operasi open-source yang menguasai **96.3% server di dunia**, termasuk semua superkomputer TOP500.\n\n**Distro Populer:** Ubuntu, Debian, Fedora, Arch Linux, CentOS\n\n**Linux menjalankan:** Server web, Android, supercomputer, IoT, cloud computing.\n\nDiciptakan oleh **Linus Torvalds** pada 1991. 🐧` },
  { keywords: ['ci/cd','continuous integration','jenkins','github actions'], response: `**CI/CD (Continuous Integration / Continuous Deployment)** adalah metode otomatisasi rilis aplikasi.\n\n- 🔄 **CI:** Otomatis test kode setiap kali ada push ke GitHub.\n- 🚀 **CD:** Otomatis deploy kode ke server jika lolos test.\n\n**Tools Populer:** GitHub Actions, GitLab CI, Jenkins, CircleCI.\n\nCI/CD membuat rilis aplikasi jadi lebih cepat, aman, dan tanpa stres! ⚙️` },

  // Programming Concepts & Paradigms
  { keywords: ['oop','object oriented','pbo','pemrograman berorientasi objek'], response: `**OOP (Object-Oriented Programming)** adalah paradigma yang mengorganisir kode ke dalam "Objek" yang memiliki data (atribut) dan perilaku (method).\n\n**4 Pilar Utama OOP:**\n1. 💊 **Encapsulation** (Membungkus data agar aman)\n2. 🧬 **Inheritance** (Pewarisan sifat dari parent ke child)\n3. 🎭 **Polymorphism** (Satu antarmuka, banyak bentuk)\n4. 👻 **Abstraction** (Menyembunyikan detail kompleks)\n\nBahasa OOP populer: Java, C#, Python, C++. 🧱` },
  { keywords: ['functional programming','fp','pemrograman fungsional'], response: `**Functional Programming (FP)** adalah paradigma yang membangun software dengan menyusun pure functions (fungsi murni) dan menghindari perubahan state (mutability).\n\n**Konsep Kunci:**\n- ✨ **Pure Functions** — Input sama selalu menghasilkan output sama.\n- 🚫 **Immutability** — Variabel tidak boleh diubah setelah dibuat.\n- 🧮 **Higher-Order Functions** — Fungsi yang menerima/mengembalikan fungsi lain (\`map\`, \`filter\`, \`reduce\`).\n\nBahasa FP populer: Haskell, Scala, Clojure (dan JS/TS banyak meminjam konsepnya)! 🧮` },
  { keywords: ['data structure','struktur data','array','linked list'], response: `**Struktur Data** adalah cara menyimpan dan mengatur data di komputer agar bisa digunakan secara efisien.\n\n**Jenis Populer:**\n- 📦 **Array** — Daftar elemen berurutan (cepat untuk diakses).\n- 🔗 **Linked List** — Elemen saling menunjuk (cepat untuk insert/delete).\n- 🥞 **Stack** — LIFO (Last In First Out) seperti tumpukan piring.\n- 🚶 **Queue** — FIFO (First In First Out) seperti antrean.\n- 🌳 **Tree & Graph** — Untuk data hierarkis dan relasional.\n- 🔑 **Hash Table / Map** — Key-value pair super cepat.\n\nPemahaman struktur data membedakan programmer biasa dan programmer hebat! 🧠` },
  { keywords: ['algoritma','algorithm','sorting','searching'], response: `**Algoritma** adalah urutan langkah logis untuk menyelesaikan masalah.\n\n**Contoh Algoritma Dasar:**\n- 🔍 **Searching:** Linear Search, Binary Search (jauh lebih cepat untuk data urut).\n- 🔄 **Sorting:** Bubble Sort, Merge Sort, Quick Sort.\n- 🗺️ **Pathfinding:** Dijkstra, A* (digunakan oleh Google Maps).\n\nAlgoritma yang baik dinilai dari efisiensinya menggunakan **Big O Notation** (seberapa cepat ia berjalan seiring bertambahnya data). ⚙️` },
  { keywords: ['big o notation','big o','kompleksitas waktu'], response: `**Big O Notation** adalah cara mengukur performa/efisiensi suatu algoritma.\n\n**Tingkatan Big O (dari cepat ke lambat):**\n- 🚀 **O(1)** — Konstan (Langsung akses indeks array)\n- ✈️ **O(log N)** — Logaritmik (Binary search)\n- 🚗 **O(N)** — Linear (Looping dari awal sampai akhir)\n- 🐢 **O(N log N)** — (Merge sort / Quick sort)\n- 🐌 **O(N²)** — Kuadratik (Nested loop, Bubble sort)\n- 💣 **O(2^N)** — Eksponensial (Brute force)\n\nAlgoritma O(1) selalu instan, sedangkan O(N²) akan sangat lambat jika datanya jutaan! ⏱️` },
  { keywords: ['design pattern','pola desain','singleton','mvc'], response: `**Design Pattern** adalah solusi standar untuk masalah umum dalam desain software.\n\n**Pattern Populer:**\n- 🏛️ **MVC (Model-View-Controller)** — Memisahkan data, UI, dan logika kontrol.\n- 🌟 **Singleton** — Memastikan hanya ada 1 instance dari sebuah class (misal: koneksi database).\n- 🏭 **Factory** — Fungsi/class yang tugasnya membuat object lain.\n- 👀 **Observer** — Model "Subscribe & Publish" (misal: event listener React).\n\nMenggunakan pattern membuat kode lebih rapi, teruji, dan standar industri. 📐` },
  { keywords: ['frontend','front end','ui','ux'], response: `**Frontend** adalah bagian dari aplikasi yang dilihat dan berinteraksi langsung dengan pengguna (Client-side).\n\n**Trio Utama Frontend Web:**\n- 🏗️ **HTML** — Struktur & Konten\n- 🎨 **CSS** — Desain & Layout\n- 🧠 **JavaScript** — Logika & Interaksi\n\n**Framework/Library Populer:** React, Vue, Angular, Svelte.\n\nFrontend Developer bertugas memastikan aplikasi berjalan lancar di berbagai perangkat, cepat, dan indah (UX/UI)! 📱` },
  { keywords: ['backend','back end','server'], response: `**Backend** adalah "dapur" dari sebuah aplikasi (Server-side). Pengguna tidak melihatnya, tapi backend-lah yang memproses data.\n\n**Tugas Backend:**\n- 🗄️ Mengelola Database (SQL/NoSQL)\n- 🔐 Autentikasi (Login/Register)\n- 📡 Membuat API untuk dikonsumsi Frontend\n- ⚙️ Memproses logika bisnis & keamanan\n\n**Bahasa Populer:** Node.js (JS), Python, Java, Go, PHP, Ruby. 🖥️` },
  { keywords: ['fullstack','full stack'], response: `**Full-Stack Developer** adalah programmer yang menguasai **Frontend sekaligus Backend**.\n\nArtinya, mereka bisa membuat UI/UX di sisi client, sekaligus merancang database dan API di sisi server. Ibarat di restoran, mereka bisa jadi pramusaji (Frontend) sekaligus koki (Backend)!\n\n**Stack Populer:**\n- **MERN:** MongoDB, Express, React, Node.js\n- **MEAN:** MongoDB, Express, Angular, Node.js\n- **LAMP:** Linux, Apache, MySQL, PHP 🤹` },
  { keywords: ['clean code','kode bersih','solid principle'], response: `**Clean Code** adalah prinsip menulis kode yang mudah dibaca, dipahami, dan dirawat oleh manusia (bukan cuma oleh komputer).\n\n**Aturan Emas Clean Code:**\n1. 🏷️ Nama variabel yang bermakna (\`let userAge\` bukan \`let a\`)\n2. 📏 Fungsi harus kecil dan hanya melakukan 1 hal (Single Responsibility)\n3. 🚫 Jangan ulangi kodemu (DRY - Don't Repeat Yourself)\n4. 📝 Komentar hanya jika kode tidak bisa menjelaskan dirinya sendiri\n\n*"Any fool can write code that a computer can understand. Good programmers write code that humans can understand."* — Martin Fowler ✨` },
  { keywords: ['agile','scrum','kanban'], response: `**Agile** adalah metodologi pengembangan software yang mengutamakan fleksibilitas, kolaborasi, dan rilis bertahap (iteratif).\n\n**Framework Agile:**\n- 🏉 **Scrum:** Dibagi dalam "Sprint" (biasanya 2 minggu). Ada peran Scrum Master, Product Owner, dan Developer.\n- 📋 **Kanban:** Menggunakan papan visual (To Do, In Progress, Done) untuk melihat alur kerja (seperti Trello).\n\nAgile menggantikan metode "Waterfall" tradisional yang kaku. 🔄` },
  { keywords: ['api rest vs graphql','graphql vs rest'], response: `**REST vs GraphQL** (Cara aplikasi bertukar data):\n\n🌐 **REST API:**\n- Standar industri, menggunakan banyak URL (endpoint) berbeda.\n- Misal: \`/users\` untuk ambil user, \`/posts\` untuk ambil post.\n- Kekurangan: Kadang mengambil data berlebih (Over-fetching) atau kurang (Under-fetching).\n\n🕸️ **GraphQL (Buatan Facebook):**\n- Hanya menggunakan 1 URL (endpoint).\n- Klien menentukan *persis* data apa yang diminta.\n- Misal: "Berikan saya nama user 1 beserta judul 3 post terakhirnya".\n- Kelebihan: Sangat efisien, pas dengan kebutuhan UI. ⚖️` },
  { keywords: ['web3','blockchain dev','solidity','smart contract'], response: `**Web3 / Blockchain Development** adalah paradigma web terdesentralisasi.\n\n**Komponen Utama:**\n- 📜 **Smart Contract:** Kode yang berjalan otomatis di blockchain (seperti Ethereum).\n- 💎 **Solidity:** Bahasa paling populer untuk menulis Smart Contract.\n- 🦊 **Metamask:** Wallet crypto penghubung Web browser dan blockchain.\n- 🌐 **dApps (Decentralized Apps):** Aplikasi yang backend-nya adalah blockchain, bukan server terpusat.\n\nKonsepnya: *Read, Write, Own* (Baca, Tulis, Miliki). ⛓️` },

  // ══════════════════════ AI & MACHINE LEARNING ══════════════════════
  { keywords: ['machine learning','ml','mesin belajar'], response: `**Machine Learning (ML)** adalah cabang AI di mana komputer **belajar dari data** tanpa diprogram eksplisit.\n\n**Jenis ML:**\n- 📊 **Supervised** — Belajar dari data berlabel\n- 🔍 **Unsupervised** — Menemukan pola tersembunyi\n- 🎮 **Reinforcement** — Belajar dari trial & error\n\n**Contoh Nyata:**\n- Spotify merekomendasikan lagu 🎵\n- Gmail mendeteksi spam 📧\n- Tesla self-driving 🚗\n- Google Translate menerjemahkan 🗣️\n\nLibrary populer: TensorFlow, PyTorch, scikit-learn 🤖` },
  { keywords: ['artificial intelligence','kecerdasan buatan','ai itu'], response: `**AI (Artificial Intelligence)** adalah bidang ilmu komputer untuk membuat mesin yang bisa **berpikir dan belajar**.\n\n**Cabang AI:**\n- 🧠 Machine Learning — Belajar dari data\n- 🗣️ NLP — Memahami bahasa manusia\n- 👁️ Computer Vision — Memahami gambar/video\n- 🤖 Robotics — Kontrol robot cerdas\n- 🎨 Generative AI — Membuat konten baru\n\n**AI di Kehidupan Sehari-hari:**\nChatGPT, Google Assistant, Face ID, YouTube Recommendations, Google Maps, dan banyak lagi!\n\nSaya (AppForge AI) juga merupakan bentuk AI! 🤖` },
  { keywords: ['chatgpt','gpt','openai'], response: `**ChatGPT** adalah chatbot AI dari **OpenAI** menggunakan model **GPT (Generative Pre-trained Transformer)**.\n\n**Versi GPT:**\n- GPT-3.5 — Gratis, cepat\n- GPT-4 — Lebih pintar, multimodal\n- GPT-4o — Teks, gambar, audio, video\n\nChatGPT dilatih dengan triliunan kata dan bisa menghasilkan teks yang sangat natural. OpenAI didirikan oleh **Sam Altman** dan kawan-kawan pada 2015. 🤖` },
  { keywords: ['gemini','google ai','bard','google gemini'], response: `**Google Gemini** (sebelumnya Bard) adalah AI chatbot dari **Google DeepMind**.\n\n**Model Gemini:**\n- ⚡ Gemini Flash — Cepat & ringan\n- 🧠 Gemini Pro — Seimbang\n- 🏆 Gemini Ultra — Paling powerful\n\nGemini bisa memproses teks, gambar, audio, dan video secara bersamaan (multimodal). Terintegrasi ke seluruh produk Google. 🔵🔴🟡🟢` },
  { keywords: ['claude','anthropic'], response: `**Claude** adalah AI chatbot dari **Anthropic**, perusahaan yang didirikan oleh mantan peneliti OpenAI.\n\nClaude terkenal karena pendekatannya yang fokus pada **keamanan AI (AI Safety)** dan kemampuan memproses dokumen yang sangat panjang (context window besar). 🟤` },
  { keywords: ['deep learning','neural network','jaringan saraf'], response: `**Deep Learning** menggunakan **Neural Network** berlapis-lapis untuk belajar dari data.\n\n**Arsitektur:**\n- 🖼️ **CNN** — Untuk gambar (pengenalan wajah, objek)\n- 📝 **RNN/LSTM** — Untuk teks sekuensial\n- 🔄 **Transformer** — Untuk bahasa (GPT, BERT, Gemini)\n- 🎨 **GAN** — Untuk generasi gambar\n- 📸 **Diffusion** — Untuk AI art (Midjourney, DALL-E)\n\nDeep Learning adalah teknologi di balik revolusi AI saat ini! 🧠` },
  { keywords: ['natural language processing','nlp','pemrosesan bahasa'], response: `**NLP (Natural Language Processing)** adalah cabang AI yang memungkinkan komputer **memahami, menginterpretasi, dan menghasilkan bahasa manusia**.\n\n**Aplikasi NLP:**\n- 🗣️ Chatbot (ChatGPT, Gemini)\n- 🌐 Google Translate\n- 📧 Deteksi Spam\n- 🔍 Search Engine\n- 📝 Auto-Complete\n\nNLP adalah teknologi inti di balik kemampuan saya memahami pertanyaan Anda! 🗣️` },
  { keywords: ['midjourney','dall-e','stable diffusion','ai art','ai image'], response: `**AI Image Generation** adalah teknologi yang membuat gambar dari teks.\n\n**Tools Populer:**\n- 🎨 **Midjourney** — Kualitas artistik tinggi\n- 🖼️ **DALL-E** (OpenAI) — Fleksibel dan kreatif\n- 🔓 **Stable Diffusion** — Open-source\n- 🎯 **Firefly** (Adobe) — Untuk profesional\n\nTeknologi ini menggunakan **Diffusion Model** yang belajar dari jutaan gambar untuk menghasilkan karya seni baru. 🎨` },

  // ══════════════════════ SAINS ══════════════════════
  { keywords: ['fisika','physics','newton','gravitasi'], response: `**Fisika** mempelajari materi, energi, dan hukum alam semesta.\n\n**Hukum Newton:**\n1. **Inersia** — Benda cenderung mempertahankan keadaannya\n2. **F = ma** — Gaya = massa × percepatan\n3. **Aksi-Reaksi** — Setiap aksi ada reaksi berlawanan\n\n**Cabang:** Kuantum, Astrofisika, Termodinamika, Relativitas\n\n**E = mc²** — Persamaan terkenal **Albert Einstein**! ⚛️` },
  { keywords: ['matematika','math','rumus','kalkulus','aljabar'], response: `**Matematika** adalah ilmu tentang angka, pola, struktur, dan logika.\n\n**Cabang Utama:**\n- 📐 Aljabar — Persamaan & variabel\n- 📊 Kalkulus — Turunan & integral\n- 📈 Statistika — Analisis data\n- 🔺 Geometri — Bentuk & ruang\n- 🎲 Probabilitas — Peluang\n\nMatematika adalah **bahasa universal** yang menjadi fondasi semua sains dan teknologi! 🔢` },
  { keywords: ['biologi','biology','sel','dna','genetika','evolusi'], response: `**Biologi** mempelajari makhluk hidup dan proses kehidupan.\n\n**Topik Penting:**\n- 🧬 DNA & Genetika — Kode kehidupan\n- 🦠 Mikrobiologi — Bakteri, virus\n- 🧠 Neurologi — Otak & sistem saraf\n- 🌿 Ekologi — Hubungan makhluk hidup & lingkungan\n- 🔬 Biologi Sel — Mitosis, meiosis\n\n**Fakta:** Tubuh manusia terdiri dari ~**37,2 triliun sel** dan ~**3 miliar** pasang basa DNA! 🧬` },
  { keywords: ['kimia','chemistry','atom','molekul','unsur','tabel periodik'], response: `**Kimia** mempelajari materi, komposisi, dan perubahannya.\n\n**Konsep Dasar:**\n- ⚛️ Atom — Unit terkecil unsur\n- 🔗 Ikatan Kimia — Ionik, kovalen\n- ⚗️ Reaksi Kimia — Perubahan zat\n- 📊 Tabel Periodik — 118 unsur\n\n**Rumus Terkenal:** H₂O (Air), NaCl (Garam), CO₂ (Karbon Dioksida), O₂ (Oksigen)\n\nKimia disebut **"Central Science"** karena menghubungkan fisika dengan biologi! ⚗️` },
  { keywords: ['astronomi','luar angkasa','galaksi','planet','tata surya','antariksa','nasa','spacex'], response: `**Astronomi** mempelajari objek dan fenomena di luar atmosfer Bumi.\n\n**Tata Surya:**\n☀️ Matahari → Merkurius → Venus → 🌍 Bumi → Mars → Jupiter → Saturnus → Uranus → Neptunus\n\n**Fakta Luar Angkasa:**\n- 🌌 Galaksi Bima Sakti punya 100-400 miliar bintang\n- 🔭 Alam semesta berumur ~13,8 miliar tahun\n- 🚀 Cahaya butuh 8 menit dari Matahari ke Bumi\n- 🪐 Jupiter bisa menampung 1.300 Bumi!\n\n**Organisasi:** NASA, ESA, SpaceX, JAXA 🚀` },

  // ══════════════════════ TOKOH TERKENAL ══════════════════════
  { keywords: ['elon musk','tesla','spacex ceo'], response: `**Elon Musk** (lahir 1971, Afrika Selatan) adalah pengusaha teknologi dan orang terkaya di dunia.\n\n**Perusahaan:**\n- 🚗 **Tesla** — Mobil listrik\n- 🚀 **SpaceX** — Roket & misi ke Mars\n- 🧠 **Neuralink** — Brain-computer interface\n- 🤖 **xAI** — AI (Grok)\n- 𝕏 **X** (Twitter) — Media sosial\n\nVisinya: Membuat umat manusia menjadi **spesies multi-planet**! 🚀` },
  { keywords: ['mark zuckerberg','facebook','meta'], response: `**Mark Zuckerberg** (lahir 1984) adalah pendiri **Facebook** (sekarang **Meta**) yang ia buat di kamar asramanya di Harvard pada 2004.\n\n**Produk Meta:**\n- 📘 Facebook (~3 miliar pengguna)\n- 📸 Instagram\n- 💬 WhatsApp\n- 🥽 Meta Quest (VR)\n- 🧵 Threads\n\nZuckerberg adalah salah satu orang terkaya di dunia! 💻` },
  { keywords: ['bill gates','microsoft founder'], response: `**Bill Gates** (lahir 1955) adalah pendiri **Microsoft** bersama Paul Allen pada 1975.\n\nGates membuat Windows dan Office yang mendominasi dunia PC. Setelah pensiun dari Microsoft, ia fokus pada filantropi melalui **Bill & Melinda Gates Foundation** untuk kesehatan global, pendidikan, dan kemiskinan.\n\nPernah menjadi orang terkaya di dunia selama bertahun-tahun. 🪟` },
  { keywords: ['steve jobs','apple founder'], response: `**Steve Jobs** (1955-2011) adalah pendiri **Apple** yang merevolusi industri teknologi.\n\n**Produk Legendaris:**\n- 🖥️ Macintosh (1984)\n- 🎵 iPod (2001)\n- 📱 iPhone (2007)\n- 📱 iPad (2010)\n\nJobs terkenal karena obsesinya terhadap **desain**, **kesederhanaan**, dan **pengalaman pengguna**. Salah satu inovator terbesar dalam sejarah! 🍎` },
  { keywords: ['albert einstein','einstein','relativitas'], response: `**Albert Einstein** (1879-1955) adalah fisikawan teoretis asal Jerman yang dianggap sebagai **ilmuwan paling berpengaruh abad ke-20**.\n\n**Kontribusi:**\n- ⚡ **E = mc²** — Kesetaraan massa-energi\n- 🌌 **Teori Relativitas Umum** — Gravitasi adalah lengkungan ruang-waktu\n- 📷 **Efek Fotolistrik** — Peraih Nobel Fisika 1921\n\nKata-kata terkenalnya: *"Imagination is more important than knowledge."* 🧠` },
  { keywords: ['nikola tesla','tesla inventor'], response: `**Nikola Tesla** (1856-1943) adalah penemu dan insinyur listrik Serbia-Amerika.\n\n**Penemuan:** Arus bolak-balik (AC), motor induksi, Tesla coil, teknologi radio.\n\nTesla bersaing dengan Thomas Edison ("War of Currents"). Sistem AC milik Tesla akhirnya memenangkan pertarungan dan menjadi standar kelistrikan dunia! ⚡` },
  { keywords: ['soekarno','sukarno','bung karno','presiden pertama'], response: `**Ir. Soekarno** (1901-1970) adalah **Presiden pertama Republik Indonesia** dan Proklamator Kemerdekaan.\n\n**Peran:** Memproklamasikan kemerdekaan Indonesia pada **17 Agustus 1945**, merumuskan Pancasila, dan memimpin negara dari 1945-1967.\n\nSoekarno dikenal sebagai orator ulung dan Bapak Bangsa Indonesia. 🇮🇩` },
  { keywords: ['joko widodo','jokowi'], response: `**Joko Widodo (Jokowi)** (lahir 1961) adalah **Presiden ke-7 Republik Indonesia** (2014-2024).\n\nSebelum menjadi presiden, ia menjabat sebagai Walikota Solo dan Gubernur DKI Jakarta. Dikenal dengan gaya kepemimpinan *"blusukan"* (turun langsung ke lapangan). 🇮🇩` },

  // ══════════════════════ NEGARA & GEOGRAFI ══════════════════════
  { keywords: ['indonesia'], response: `🇮🇩 **Republik Indonesia**\n\n- 🏝️ **17.508 pulau** — Negara kepulauan terbesar\n- 👥 **280+ juta** penduduk — Terbesar ke-4 di dunia\n- 🗣️ **700+ bahasa daerah**\n- 🏛️ Ibu Kota: Jakarta → IKN Nusantara\n- 🌏 Semboyan: *Bhinneka Tunggal Ika*\n- 💰 Mata uang: Rupiah (IDR)\n- 🕌 Negara berpenduduk Muslim terbesar di dunia\n\nIndonesia terkenal dengan Bali, Borobudur, Komodo, dan rendang! 🇮🇩` },
  { keywords: ['amerika','united states','usa','amerika serikat'], response: `🇺🇸 **Amerika Serikat (USA)**\n\n- 👥 **330+ juta** penduduk\n- 🏛️ Ibu Kota: Washington, D.C.\n- 💰 Ekonomi terbesar di dunia (GDP ~$25 triliun)\n- 🗽 50 negara bagian\n- 🚀 Pusat inovasi teknologi (Silicon Valley)\n- 🎬 Pusat industri hiburan (Hollywood)\n\nAS adalah rumah bagi perusahaan seperti Apple, Google, Amazon, dan Microsoft. 🇺🇸` },
  { keywords: ['jepang','japan','nippon'], response: `🇯🇵 **Jepang (Japan)**\n\n- 👥 **125 juta** penduduk\n- 🏛️ Ibu Kota: Tokyo\n- 💰 Ekonomi terbesar ke-3 di dunia\n- 🎌 Terkenal: Anime, manga, sushi, teknologi\n- 🏯 Budaya: Samurai, geisha, cherry blossom\n- 🚄 Shinkansen (kereta cepat)\n\nJepang menggabungkan tradisi kuno dengan teknologi tercanggih! 🇯🇵` },
  { keywords: ['korea','korea selatan','south korea','kpop','kdrama'], response: `🇰🇷 **Korea Selatan**\n\n- 👥 **51 juta** penduduk\n- 🏛️ Ibu Kota: Seoul\n- 🎵 **K-Pop** — BTS, BLACKPINK, aespa\n- 📺 **K-Drama** — Squid Game, Crash Landing\n- 📱 **Samsung, LG, Hyundai**\n- 🎮 Negara esports terkuat\n\nKorean Wave (Hallyu) telah mendunia! 🇰🇷` },
  { keywords: ['china','tiongkok','cina'], response: `🇨🇳 **China (Tiongkok)**\n\n- 👥 **1,4 miliar** penduduk (terbanyak ke-2)\n- 🏛️ Ibu Kota: Beijing\n- 💰 Ekonomi terbesar ke-2 di dunia\n- 🏗️ Great Wall, Forbidden City\n- 📱 Tech: Huawei, Alibaba, TikTok, WeChat\n\nChina adalah kekuatan ekonomi dan teknologi global! 🇨🇳` },

  // ══════════════════════ BISNIS & EKONOMI ══════════════════════
  { keywords: ['startup','bisnis','business','entrepreneurship','wirausaha'], response: `**Startup** adalah perusahaan rintisan yang dirancang untuk tumbuh cepat dengan inovasi.\n\n**Unicorn Indonesia:** Gojek, Tokopedia (GoTo), Traveloka, Bukalapak, OVO\n\n**Tips Memulai Startup:**\n1. 💡 Temukan masalah nyata\n2. 📊 Validasi dengan MVP\n3. 👥 Bangun tim yang solid\n4. 💰 Cari funding (bootstrapping, angel investor, VC)\n5. 📈 Scale & iterate\n\nStartup terbesar di dunia: Apple, Google, Amazon, Meta — semuanya dimulai dari garasi! 🚀` },
  { keywords: ['investasi','saham','stock','crypto','reksadana','invest'], response: `**Investasi** adalah menempatkan uang/aset dengan harapan mendapat keuntungan di masa depan.\n\n**Jenis Investasi:**\n- 📈 **Saham** — Membeli kepemilikan perusahaan\n- 🏦 **Obligasi** — Surat utang\n- 🏠 **Properti** — Tanah, rumah\n- 💰 **Reksadana** — Dikelola manajer investasi\n- ₿ **Crypto** — Aset digital\n- 🥇 **Emas** — Safe haven\n\n**Prinsip:** *"Don't put all your eggs in one basket"* — Diversifikasi! 💹` },

  // ══════════════════════ KESEHATAN ══════════════════════
  { keywords: ['kesehatan','health','sehat','penyakit','dokter'], response: `**Tips Hidup Sehat:**\n\n- 🥗 **Nutrisi** — Makan seimbang (sayur, buah, protein)\n- 🏃 **Olahraga** — Min. 150 menit/minggu\n- 😴 **Tidur** — 7-9 jam/malam\n- 💧 **Hidrasi** — Min. 8 gelas air/hari\n- 🧘 **Mental Health** — Kelola stres, meditasi\n- 🚭 Hindari rokok & alkohol berlebihan\n\n⚠️ *Saya AI, bukan dokter. Untuk keluhan kesehatan serius, selalu konsultasikan ke profesional medis.*` },

  // ══════════════════════ OLAHRAGA ══════════════════════
  { keywords: ['sepak bola','football','soccer','bola','fifa','piala dunia','world cup'], response: `⚽ **Sepak Bola** adalah olahraga paling populer di dunia dengan **4 miliar penggemar**.\n\n**Kompetisi Top:**\n- 🏆 FIFA World Cup\n- 🏆 UEFA Champions League\n- 🏴 Premier League (Inggris)\n- 🇪🇸 La Liga (Spanyol)\n- 🇮🇹 Serie A (Italia)\n\n**Legenda:** Pelé, Maradona, Messi, Ronaldo, Zidane\n\n**Pemenang World Cup terbanyak:** Brasil (5 kali) 🇧🇷` },
  { keywords: ['basket','basketball','nba'], response: `🏀 **Basket (Basketball)** diciptakan oleh **James Naismith** pada 1891 di Amerika.\n\n**NBA** adalah liga basket paling prestisius di dunia.\n\n**Legenda:** Michael Jordan, LeBron James, Kobe Bryant, Stephen Curry\n\nTimnas basket AS mendominasi Olimpiade dengan 16 medali emas! 🏀` },

  // ══════════════════════ HIBURAN ══════════════════════
  { keywords: ['film','movie','bioskop','cinema','netflix','disney'], response: `🎬 **Film & Industri Hiburan**\n\n**Film Terlaris Sepanjang Masa:**\n1. 🔵 Avatar ($2.9M)\n2. 🦸 Avengers: Endgame ($2.8M)\n3. 🚢 Titanic ($2.2M)\n\n**Platform Streaming:** Netflix, Disney+, HBO Max, Amazon Prime\n\n**Studio Besar:** Walt Disney, Warner Bros, Universal, Paramount, Sony\n\nIndustri film global bernilai lebih dari **$100 miliar**! 🎬` },
  { keywords: ['musik','music','lagu','song','spotify','genre'], response: `🎵 **Musik** adalah bentuk seni yang menggunakan suara dan ritme.\n\n**Genre Populer:** Pop, Rock, Hip-Hop, R&B, EDM, Jazz, Klasik, K-Pop, Dangdut\n\n**Platform:** Spotify (600M+ users), Apple Music, YouTube Music\n\n**Artis Terpopuler (Spotify):** The Weeknd, Taylor Swift, Ed Sheeran, BTS, Bad Bunny\n\nMusik adalah bahasa universal yang menyatukan manusia! 🎶` },
  { keywords: ['game','gaming','esports','video game','gamer'], response: `🎮 **Gaming & Esports**\n\n**Genre Game:**\n- 🎯 FPS — Valorant, CS2, Call of Duty\n- ⚔️ MOBA — Mobile Legends, Dota 2, LoL\n- 🌍 Open World — GTA, Zelda, Elden Ring\n- ⛏️ Survival — Minecraft, Fortnite\n\n**Esports** adalah industri yang bernilai $1.8 miliar.\n\n**Platform:** PC, PlayStation, Xbox, Nintendo Switch, Mobile 🎮` },
  { keywords: ['anime','manga','jepang animation'], response: `🎌 **Anime & Manga** adalah industri hiburan Jepang yang mendunia.\n\n**Anime Terpopuler:**\n- ⚔️ Attack on Titan\n- 👹 Demon Slayer\n- 🍥 Naruto & One Piece\n- 💀 Jujutsu Kaisen\n- 🐉 Dragon Ball\n\n**Studio:** MAPPA, Ufotable, Kyoto Animation, Wit Studio\n\nIndustri anime global bernilai **$25+ miliar**! 🎌` },

  // ══════════════════════ PENDIDIKAN ══════════════════════
  { keywords: ['belajar','study','tips belajar','belajar coding','belajar programming'], response: `📚 **Tips Belajar Efektif:**\n\n1. 🎯 **Pomodoro Technique** — 25 menit fokus, 5 menit istirahat\n2. 📝 **Active Recall** — Uji diri sendiri, jangan cuma baca\n3. 🔄 **Spaced Repetition** — Ulang materi secara berkala\n4. 🧠 **Feynman Technique** — Jelaskan ke orang lain\n5. 🚫 **Matikan distraksi** — HP silent, fokus!\n\n**Untuk Belajar Coding:**\n- Mulai dari Python atau JavaScript\n- Sumber gratis: freeCodeCamp, YouTube, MDN\n- Buat proyek nyata (kalkulator, todo app)\n- Konsisten 30 menit/hari > 5 jam sekali seminggu\n\n*"Education is not the filling of a pail, but the lighting of a fire."* — W.B. Yeats 📚` },

  // ══════════════════════ SOSIAL MEDIA ══════════════════════
  { keywords: ['tiktok','social media','sosial media','instagram','youtube','twitter','x'], response: `📱 **Media Sosial** menghubungkan miliaran orang di seluruh dunia.\n\n**Platform Terbesar (2024):**\n- 📘 **Facebook** — 3 miliar users\n- 📺 **YouTube** — 2.5 miliar users\n- 💬 **WhatsApp** — 2.7 miliar users\n- 📸 **Instagram** — 2 miliar users\n- 🎵 **TikTok** — 1.5 miliar users\n- 𝕏 **X (Twitter)** — 500 juta users\n\nMedia sosial mengubah cara manusia berkomunikasi, berbisnis, dan mengonsumsi informasi! 📱` },
];

// ── Levenshtein Distance (typo tolerance) ─────────────────────
function levenshtein(a: string, b: string): number {
  const matrix: number[][] = [];
  for (let i = 0; i <= a.length; i++) matrix[i] = [i];
  for (let j = 0; j <= b.length; j++) matrix[0][j] = j;
  for (let i = 1; i <= a.length; i++) {
    for (let j = 1; j <= b.length; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      matrix[i][j] = Math.min(
        matrix[i - 1][j] + 1,
        matrix[i][j - 1] + 1,
        matrix[i - 1][j - 1] + cost
      );
    }
  }
  return matrix[a.length][b.length];
}

function isFuzzyMatch(word: string, keyword: string): boolean {
  if (word === keyword) return true;
  if (word.length < 3 || keyword.length < 3) return word === keyword;
  // Allow up to ~30% character errors
  const maxDistance = Math.max(1, Math.floor(keyword.length * 0.3));
  return levenshtein(word, keyword) <= maxDistance;
}

// ── Fuzzy Keyword Matching Engine ──────────────────────────────

export function searchLocalBrain(input: string): string | null {
  const q = input.toLowerCase().replace(/[?.,!'"]/g, '').trim();
  
  if (!q || q.length < 2) return null;

  let bestMatch: KnowledgeEntry | null = null;
  let bestScore = 0;

  const words = q.split(/\s+/);

  for (const entry of KB) {
    let score = 0;
    for (const keyword of entry.keywords) {
      // Full phrase match (highest priority)
      if (q.includes(keyword)) {
        score += keyword.length * 4;
        continue;
      }
      // Per-word matching with fuzzy tolerance
      for (const word of words) {
        if (word === keyword) {
          score += keyword.length * 5; // Exact word = highest
        } else if (isFuzzyMatch(word, keyword)) {
          score += keyword.length * 3; // Fuzzy match = high
        } else if (keyword.length > 3 && word.includes(keyword)) {
          score += keyword.length * 2;
        } else if (keyword.length > 3 && keyword.includes(word) && word.length > 3) {
          score += word.length;
        }
      }
    }
    
    if (score > bestScore) {
      bestScore = score;
      bestMatch = entry;
    }
  }

  if (bestMatch && bestScore >= 4) {
    return bestMatch.response;
  }

  return null;
}

// ── Multi-Match Search (for Reasoning Engine) ─────────────────

export interface BrainMatch {
  response: string;
  score: number;
  topKeyword: string;
}

/**
 * Returns the top N knowledge base matches above a threshold.
 * Used by the reasoning engine to combine multiple relevant topics.
 */
export function searchLocalBrainMulti(input: string, maxResults: number = 3): BrainMatch[] {
  const q = input.toLowerCase().replace(/[?.,!'"]/g, '').trim();
  if (!q || q.length < 2) return [];

  const words = q.split(/\s+/);
  const scored: { entry: KnowledgeEntry; score: number; topKeyword: string }[] = [];

  for (const entry of KB) {
    let score = 0;
    let topKeyword = entry.keywords[0] || '';
    let topKeywordScore = 0;

    for (const keyword of entry.keywords) {
      let kwScore = 0;

      // Full phrase match
      if (q.includes(keyword)) {
        kwScore += keyword.length * 4;
      }

      // Per-word matching with fuzzy tolerance
      for (const word of words) {
        if (word === keyword) {
          kwScore += keyword.length * 5;
        } else if (isFuzzyMatch(word, keyword)) {
          kwScore += keyword.length * 3;
        } else if (keyword.length > 3 && word.includes(keyword)) {
          kwScore += keyword.length * 2;
        } else if (keyword.length > 3 && keyword.includes(word) && word.length > 3) {
          kwScore += word.length;
        }
      }

      score += kwScore;
      if (kwScore > topKeywordScore) {
        topKeywordScore = kwScore;
        topKeyword = keyword;
      }
    }

    if (score >= 4) {
      scored.push({ entry, score, topKeyword });
    }
  }

  // Sort by score descending and take top N
  scored.sort((a, b) => b.score - a.score);

  return scored.slice(0, maxResults).map(s => ({
    response: s.entry.response,
    score: s.score,
    topKeyword: s.topKeyword,
  }));
}
